Kisisel_Web_Sitesi/Controllers/AnasayfaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kisisel_Web_Sitesi.Controllers
{
    public class AnasayfaController : Controller
    {
        // GET: Anasayfa
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Hakkimda()
        {
            return View();
        }

        public ActionResult Skills()
        {
            return View();
        }
        public ActionResult Works()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return View();
        }
    }
}

Kisisel_Web_Sitesi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kisisel_Web_Sitesi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Kisisel_Web_Sitesi/Views/Anasayfa/Contact.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Murat Emre ATEŞ | İletişim</title>
    <link rel="stylesheet" href="~/web-Web Sitem/contact.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
    
<div class="sosyalbutonlar">
    <a href="https://www.facebook.com/ats.emre" target="_blank" class="facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a>
    <a href="https://twitter.com/muratemreats" target="_blank" class="twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a>
    <a href="https://github.com/muratemreates" target="_blank" class="github" ><aria-hidden= class="fa fa-github" aria-hidden="true"></i></a>
    <a href="https://instagram.com/muratemreats" target="_blank" class="instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a>
    <a href="https://www.linkedin.com/in/muratemreates/" target="_blank" class="linkedin" ><aria-hidden= class="fa fa-linkedin" aria-hidden="true"></i></a>
    <a href="http://t.me/mrtemreats" target="_blank" class="telegram" ><i class="fa fa-telegram" aria-hidden="true"></i></a>
    <a  mail href="mailto:m.emre6530@gmail.com" target="_blank" class="youtube"><i class="fa fa-google" aria-hidden="true"></i></a>   
</div>
</body>
</html>

Kisisel_Web_Sitesi/Views/Anasayfa/Hakkimda.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Murat Emre ATEŞ | Hakkımda</title>
    <link rel="stylesheet" href="~/web-Web Sitem/hakkimda.css">
</head>
<body>
<div class="row">
    <div class="column" id="hakkimda">
        <h1> HAKKIMDA</h1>
        <h3> Merhaba ben Murat Emre ATEŞ,Van Yüzüncü Yıl Üniversitesi Bilgisayar Programcılığı 2. sınıf öğrencisiyim.</h3>
        <p>2022 yılında kazandığım bu bölümde kendimi mobil uygulamalar, Unity ile Oyun geliştirme,Veri Tabanı (MSSQL), .Net alanlarında geliştirmekteyim. Mobil uygulama ve Otomasyon üzerinde projelerim bulunmaktadır.</p>
    </div>
    <div class="column" >
        <img id="resim" src="~/web-Web Sitem/assets/mea.gif" alt="">
    </div>
</div>
<div class="row" id="ft">
    <div class="column" id="foto">
        <img id="resimler" src="~/web-Web Sitem/assets\ankara.jpg">
    </div>

    <div class="column" id="foto">
        <img id="resimler"  src="~/web-Web Sitem/assets\sahil.jpg">
    </div>

    <div class="column" id="foto">
        <img id="resimler"  src="~/web-Web Sitem/assets\van.jpg">
    </div>
</div>

</body>
</html>

Kisisel_Web_Sitesi/Views/Anasayfa/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Murat Emre Ateş | Ana Sayfa</title>
    <link rel="stylesheet" href="~/web-Web Sitem/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
</head>
<body>
    
<div class="row" id="satir1">
    <div class="column" id="ben">
            
        <div class="content" id="yazi">
            <h1>Murat Emre Ateş</h1>
            <h2>Backend Developer</h2>
                
        </div> 
    </div>
    <div class="column" id="hakkimda">  
        <p>ABOUT ME</p> 
    </div>
    <script>
        document.getElementById("hakkimda").addEventListener("click", function() {
            window.location.href = "@Url.Action("Hakkimda","Anasayfa")"; // Yönlendirilecek URL'yi belirtin
});
    </script>   
</div>


<div class="row" id="satir2">
    <div class="column" id="skills"> SKILLS</div>
    <div class="column" id="works">WORKS</div>
    <div class="column" id="contact">CONTACT</div>
    <script>
            document.getElementById("skills").addEventListener("click", function() {
        window.location.href = "@Url.Action("Skills","Anasayfa")"; // Yönlendirilecek URL'yi belirtin
    });
    document.getElementById("works").addEventListener("click", function() {
        window.location.href = "@Url.Action("Works","Anasayfa")"; // Yönlendirilecek URL'yi belirtin
    });
    document.getElementById("contact").addEventListener("click", function() {
        window.location.href = "@Url.Action("Contact","Anasayfa")"; // Yönlendirilecek URL'yi belirtin
    });
        </script>   

</div>
</body>
</html>

Kisisel_Web_Sitesi/Views/Anasayfa/Skills.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Murat Emre  ATEŞ - Yetenekler</title>
    <link rel="stylesheet" href="~/web-Web Sitem/skills.css">
</head>
<body>
<div class="row">
    <img src="~/web-Web Sitem/assets/c_sarp.png" id="logo">
    <img src="~/web-Web Sitem/assets/Python.png" id="logo">
    <img src="~/web-Web Sitem/assets/flutter.png" id="logo">
    <img src="~/web-Web Sitem/assets/dart.png" id="logo">
    <img src="~/web-Web Sitem/assets/mssql-server.png" id="logo">
    <img src="~/web-Web Sitem/assets/unity.png" id="logo">
</div>
</body>
</html>

Kisisel_Web_Sitesi/Views/Anasayfa/Works.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Murat Emre ATEŞ | Çalışmalar</title>
    <link rel="stylesheet" href="~/web-Web Sitem/works.css">
</head>
<body>
<div class="row" id="satir2">
    <div class="column" id="skills"> YEMEK UYGULAMASI</div>
    <div class="column" id="works">OTOPARK OTOMASYONU</div>
    <div class="column" id="contact">SAVAŞ OYUNU</div>
    <script>
document.getElementById("skills").addEventListener("click", function() {
    window.open("https://github.com/muratemreates/Yemek_Uygulamasi_bitirme_projesi", "_blank");
});
document.getElementById("works").addEventListener("click", function() {
        window.location.href = "index.html"; // Yönlendirilecek URL'yi belirtin
    });
    document.getElementById("contact").addEventListener("click", function() {
    window.open("https://github.com/muratemreates/Counter-Attack", "_blank");
});
        </script>
</div>
</body>
</html>

Kisisel_Web_Sitesi/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Kisisel_Web_Sitesi/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Kisisel_Web_Sitesi/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Kisisel_Web_Sitesi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>